# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Open Healthcare Network
theme:
  logo: assets/logo/PNG/light_logo.png
  name: material
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode